name: Docker Publish

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    uses: cabrera-evil/workflows/.github/workflows/publish-npm.yaml@master
    with:
      npm_token_ref: op://actions/NPM/credential
    secrets: inherit
